# Generated by Django 5.2 on 2025-04-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment_screenshot_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created_at']},
        ),
    ]
