# Generated by Django 5.2 on 2025-04-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_bill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={},
        ),
        migrations.AddField(
            model_name='sharedbill',
            name='distributed',
            field=models.BooleanField(default=False),
        ),
    ]
