# Generated by Django 5.2 on 2025-04-06 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_expense'),
        ('residents', '0003_resident_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='residents.resident'),
        ),
    ]
