# Generated by Django 5.2 on 2025-04-06 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_expense_resident'),
        ('residents', '0003_resident_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='If true, this expense will be shared among all active residents'),
        ),
        migrations.AddField(
            model_name='expense',
            name='share_distributed',
            field=models.BooleanField(default=False, help_text='Indicates if the expense has been distributed among residents'),
        ),
        migrations.CreateModel(
            name='ResidentExpenseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_shares', to='billing.expense')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_shares', to='residents.resident')),
            ],
            options={
                'unique_together': {('expense', 'resident')},
            },
        ),
    ]
