# Generated by Django 4.2.20 on 2025-05-28 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0010_bill_payment_date_bill_payment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='union_leader',
            field=models.ForeignKey(blank=True, help_text='The union leader/admin responsible for this bill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='union_leader',
            field=models.ForeignKey(blank=True, help_text='The union leader/admin responsible for this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedbill',
            name='union_leader',
            field=models.ForeignKey(blank=True, help_text='The union leader/admin responsible for this bill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_bills', to=settings.AUTH_USER_MODEL),
        ),
    ]
