# Generated by Django 4.2.20 on 2025-05-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_bill_union_leader_expense_union_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
