# Generated by Django 4.2.20 on 2025-05-29 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_bill_penalty_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentexpenseshare',
            name='bill',
            field=models.OneToOneField(blank=True, help_text='The bill for this resident expense share', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_share', to='billing.bill'),
        ),
    ]
