# Generated by Django 4.2.20 on 2025-05-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_residentexpenseshare_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('maintenance', 'Maintenance'), ('salaries', 'Salaries'), ('marketing', 'Marketing'), ('insurance', 'Insurance'), ('taxes', 'Taxes'), ('other', 'Other'), ('shared_expense', 'Shared Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sharedbill',
            name='bill_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('maintenance', 'Maintenance'), ('salaries', 'Salaries'), ('marketing', 'Marketing'), ('insurance', 'Insurance'), ('taxes', 'Taxes'), ('other', 'Other'), ('shared_expense', 'Shared Expense')], max_length=20),
        ),
    ]
