# Generated by Django 4.2.20 on 2025-05-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_bill_bill_type_alter_sharedbill_bill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='is_shared',
            field=models.BooleanField(default=True, help_text='If true, this expense will be shared among all active residents'),
        ),
    ]
