# Generated by Django 5.2 on 2025-04-06 17:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='size_sqft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='resident',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='unit_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='residents.property'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('security', 'Security'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=True, help_text='If true, expense is divided among residents')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='residents.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
