# Generated by Django 5.2 on 2025-04-06 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
        ('residents', '0002_property_size_sqft_resident_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='homes.home'),
        ),
    ]
