# Generated by Django 5.2 on 2025-04-08 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
        ('residents', '0003_resident_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='property',
        ),
        migrations.AddField(
            model_name='resident',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resident',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='homes.home'),
        ),
    ]
