# Generated by Django 5.2 on 2025-04-08 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
        ('residents', '0004_remove_resident_property_resident_is_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='property',
        ),
        migrations.AddField(
            model_name='expense',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='homes.home'),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
