# Generated by Django 4.2.20 on 2025-05-28 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residents', '0005_remove_expense_property_expense_home_delete_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='union_leader',
            field=models.ForeignKey(blank=True, help_text='The union leader/admin responsible for this resident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_residents', to=settings.AUTH_USER_MODEL),
        ),
    ]
