# Generated by Django 5.2 on 2025-04-06 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.AddField(
            model_name='staff',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='staff.staffrole'),
        ),
    ]
