# Generated by Django 5.2 on 2025-04-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
