# Generated by Django 5.2 on 2025-04-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default='FirstName', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='LastName', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='national_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
